[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/sitemap.xsl"
  [headers.values]
    Content-Type = "text/xsl; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = false

[[redirects]]
  from = "/sitemap.xsl"
  to = "/sitemap.xsl"
  status = 200
  force = false

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
